service_sensor:
  direct_db_write: false
  db:
    host: 'localhost'
    name: 'chart-ng'
    login: 'chart'
    pass: 'chart'
  use_rabbitmq: true
  rabbitmq:
    ip: 'localhost'
    port: 5672
    timeout: 5
    user: 'admin'
    password: 'admin'
    queue: 'sensor'
  device:
    dht:
      loldht: '/../../bin/loldht/loldht'
      pin:  7
      ticker: 600
    peacefair:
      uart: '/dev/ttyS0'
      ticker: 1
    bmp280:
      ticker: 5
  output:
    to:
      stdout: false
      syslog: true
    level: 'info'
    ident: 'ServiceSensor'
