db:
  host: 'localhost'
  name: 'chart-ng'
  login: 'chart'
  pass: 'chart'
names:
  28-04175021d3ff:  'Датчик 1 отключен'
  28-041750878dff:  'Кухня'
  28-0417503c27ff:  'Котёл выход'
  28-0417504b52ff:  'Котёл приход с гаража'
  28-041750859bff:  'Котёл вход'

