cli:
  db:
    host: 'localhost'
    name: 'chart-ng'
    login: 'chart'
    pass: 'chart'
  rabbitmq:
    ip: 'localhost'
    port: 5672
    user: 'admin'
    password: 'admin'
    queue: 'sensor'
    ack: true
  device:
    dht:
      loldht: '/../../bin/loldht/loldht'
      pin:  7
    peacefair:
      uart: '/dev/ttyS0'
  direct_db_write: false
  use_rabbitmq: true
  stdout: true
  debug:  false

web:
  db:
    host: 'localhost'
    name: 'chart-ng'
    login: 'chart'
    pass: 'chart'
  rabbitmq:
    ip: 'localhost'
    port: 5672
    user: 'admin'
    password: 'admin'
    queue: 'sensor'
  names:
    28-04175021d3ff:  'Датчик 1 отключен'
    28-041750878dff:  'Кухня'
    28-0417503c27ff:  'Котёл выход'
    28-0417504b52ff:  'Котёл приход с гаража'
    28-041750859bff:  'Котёл вход'
  stdout: true
  debug:  false

